# help
# version: '3.9' # not use anymore

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anboisve/data/mariadb
  
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anboisve/data/wordpress

networks:
  inception:
    driver: bridge

#
