# help
#
# https://kbremaud.fr/linux/installer-nginx-avec-docker-compose/

# version: '3.9' # not use anymore

services:
  nginx:
    build: ./requirements/nginx
    dockerfile: Dockerfile
#  volume:
#    - worlpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always
#

mariadb