#nginx
#TLSv1.2 or TLSv1.3
#https://mpolinowski.github.io/docs/DevOps/NGINX/2020-08-27--nginx-docker-ssl-certs-self-signed/2020-08-27/
#Alpine Linux
#Debian Buster
FROM Debian:Buster
RUN 

EXPOSE 8080